### ISSUE TITLE
Utilisation impossible sur les navigateurs sans $_SERVER["HTTP_REFERER"]

### ISSUE THREAD

**Issue by Deevad** [Pluxopolis/plxMyMultiLingue#5]
Bonjour, j'utilise plxMyMultiLingue sur http://www.peppercarrot.com/ et un contributeur m'a souligné que le site était paralysé si un navigateur sans support de la fonction HTTP_REFERER naviguait dessus. Ceci arrive en partie car certains navigateurs avec ou sans plugin désactivent cette fonction pour ne pas être tracé sur le net (je suppose). Cela concerne donc une (toute) petite audience de visiteurs à mon avis, mais soucieux de leur sécurité.

Le contributeur m'a renvoyé à une citation de la documentation Php: 

> 'HTTP_REFERER'
> L'adresse de la page (si elle existe) qui a conduit le client à la page courante. Cette valeur est affectée par le client, et tous les clients ne le font pas. Certains navigateurs permettent même de modifier la valeur de HTTP_REFERER, sous forme de fonctionnalité. En bref, ce n'est pas une valeur de confiance.
> ( http://php.net/manual/fr/reserved.variables.server.php )

Pour reproduire le bug en local:
![2016-05-30_screenshot_001](https://cloud.githubusercontent.com/assets/4021867/15655303/2d9d4f36-269c-11e6-8045-fe78930c8ebc.png)
Firefox permet de désactiver le Referer dans about:config ; je place ici une copie d'écran de comment désactiver le referer en trois étape. Une fois fait; il suffit de changer de langue sur le site pour arriver sur une page d’erreur. 

J'ai lue des avis sur http://stackoverflow.com/questions/12369615/serverhttp-referer-missing  pour essayer de contribuer à cette correction, mais les changements encouragés ( transmition de l'URL précedante dans l'URL active par variable ) dépassent le champs de mes compétences sur un plugin aussi complexe et sophistiqué... Je rapporte donc le bug au projet principale; pour au moins que ce soit connu et enregistré quelque-part.

**Comment by Pluxopolis** [comment]
L'utilisation de $_SERVER["HTTP_REFERER"] a été supprimée dans la version 0.8 en cours de dev.
Il ne devrait plus avoir le bug

**Comment by Deevad** [comment]
@Pluxopolis : Un grand merci!

**Comment by jerrywham** [comment]
Je confirme. Si on prend la version 0.8, le bug est corrigé.
