### ISSUE TITLE
Adding lang "sk" into the path of link in url field of the slide...

### ISSUE THREAD

**Issue by dadoprom** [Pluxopolis/plxMyMultiLingue#8]
it behaves like this

in plugin MySlippry
... each time clicking on "update image list" (slides) in administration it adds another instance of "sk" into the url. 

Same happens for links inside any article - on every "save" of article it adds another instance of "sk" into the path. What I have noticed is: it does not happen if Multilingue plugin is deactivated... so it looks like it is MultiLingue Specific issue.

Example from MySlippry:
this is the correct link of article: sk/article10/porod
after I click "update image list" the link looks like this: sk/sk/article10/porod

Next time I click "update image list" happens this: sk/sk/sk/article10/porod

and so on...
Same happens with links inside articles...
Same happens with other language like EN or DE... it just depends on in which language I am adding content, than it adds EN or DE into url...

I use pluxml 5.6 latest rc and MultiLingue - Version 0.8 latest rc with slovak language mutation - working on the translation... at the moment it is just a copy of EN language

If you can not reproduce the issue, should I send you zipped pluxml or should I give you access to my site for you to see?

Best regards

David

**Comment by dadoprom** [comment]
![bug](https://cloud.githubusercontent.com/assets/19377506/23669716/701f83aa-0365-11e7-9597-451d9ce659eb.png)
see screensot...

**Comment by dadoprom** [comment]
I did some testing, the issue does not occur with plugin MyBetterUrls - Version 1.5.4 enabled and configured...

**Comment by Pluxopolis** [comment]
Hello David. 

Thanks for your feedback.
I found where the issue comes from. It comes from the plugin plxMyMultiLingue. 
I will publish a fix of this plugin soon as a new pre-release of PluXml, because it requires fixes too.

Regards
Stéphane

**Comment by Pluxopolis** [comment]
Please check the latest pre-releases of PluXml and plxMyMultiLingue. This bug should be fixed now

**Comment by dadoprom** [comment]
Hellou,
I did quick testing. Behaves as expected, All is allright.
